# Generated by Django 5.2.7 on 2025-10-17 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('PRE', 'Pré-Definida'), ('PER', 'Personalizada')], default='PRE', max_length=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('duracao_estimada', models.PositiveIntegerField(help_text='Duração estimada em minutos')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_principal.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField()),
                ('duracao_estimada', models.PositiveIntegerField(help_text='Duração estimada em minutos')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='app_principal.trilha')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
