# Generated by Django 5.2.7 on 2025-10-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='duracao_estimada',
            field=models.PositiveIntegerField(default=0, help_text='Duração estimada em minutos'),
        ),
    ]
