# Generated by Django 5.2.7 on 2025-11-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0004_alter_etapa_duracao_estimada_alter_inscricao_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Minha Inscrição', 'verbose_name_plural': 'Minhas Inscrições'},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
    ]
