# Generated by Django 5.2.7 on 2025-11-02 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0005_alter_inscricao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['data_inscricao']},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('usuario', 'trilha')},
        ),
    ]
