# Generated by Django 5.2.7 on 2025-11-02 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0006_alter_inscricao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['ordem'], 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['data_inscricao'], 'verbose_name': 'Minha Inscrição', 'verbose_name_plural': 'Minhas Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
