# Generated by Django 5.2.7 on 2025-11-02 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0007_alter_categoria_options_alter_etapa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_etapa', to='app_principal.etapa')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_trilha', to='app_principal.trilha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso',
                'verbose_name_plural': 'Progresso dos Alunos',
                'unique_together': {('usuario', 'etapa')},
            },
        ),
    ]
