# Generated by Django 5.2.7 on 2025-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0009_alter_inscricao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='conteudo_texto',
            field=models.TextField(blank=True, help_text='Texto ou resumo da etapa', null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do vídeo da etapa (MP4 ou YouTube)', null=True),
        ),
    ]
