# Generated by Django 5.2.7 on 2025-10-25 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_principal', '0002_alter_trilha_duracao_estimada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='app_principal.etapa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_etapas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_conclusao'],
                'unique_together': {('usuario', 'etapa')},
            },
        ),
    ]
