# Generated by Django 5.2.7 on 2025-11-06 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0009_alter_inscricao_usuario'),
        ('area_estudante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.FloatField(default=0.0)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='app_principal.trilha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
